# netlify.toml

[build]
  # Katalog zawierający pliki front-endu do opublikowania
  publish = "." 
  
  # Katalog, w którym Netlify znajdzie funkcje Serverless
  functions = "netlify/functions"
  
  # Komenda uruchamiana podczas budowania
  command = "npm install" 

[functions]
  # Użycie nowoczesnego bundlera ESBuild
  node_bundler = "esbuild"

# Ustawienia nagłówków HTTP (dla CORS)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"